(function(){(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},n="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ba=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");
},ca=ba(this),p=function(a,b){if(b)a:{var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&n(c,a,{configurable:!0,writable:!0,value:b})}};
p("Symbol",function(a){if(a)return a;var b=function(f,l){this.g=f;n(this,"description",{configurable:!0,writable:!0,value:l})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
p("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ca[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&n(d.prototype,a,{configurable:!0,writable:!0,value:function(){return da(aa(this))}})}return a});
var da=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},q=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}},ea="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var ka=fa,la=function(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ca=b.prototype},r=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
p("WeakMap",function(a){function b(){}function c(h){var k=typeof h;return"object"===k&&null!==h||"function"===k}function d(h){if(!r(h,f)){var k=new b;n(h,f,{value:k})}}function e(h){var k=Object[h];k&&(Object[h]=function(m){if(m instanceof b)return m;Object.isExtensible(m)&&d(m);return k(m)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),k=Object.seal({}),m=new a([[h,2],[k,3]]);if(2!=m.get(h)||3!=m.get(k))return!1;m.delete(h);m.set(k,4);return!m.has(h)&&4==m.get(k)}catch(G){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var l=0,g=function(h){this.g=(l+=Math.random()+1).toString();if(h){h=q(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}};g.prototype.set=function(h,k){if(!c(h))throw Error("Invalid WeakMap key");d(h);if(!r(h,f))throw Error("WeakMap key fail: "+h);h[f][this.g]=k;return this};g.prototype.get=function(h){return c(h)&&r(h,f)?h[f][this.g]:void 0};g.prototype.has=function(h){return c(h)&&r(h,f)&&r(h[f],this.g)};
g.prototype.delete=function(h){return c(h)&&r(h,f)&&r(h[f],this.g)?delete h[f][this.g]:!1};return g});
p("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),h=new a(q([[g,"s"]]));if("s"!=h.get(g)||1!=h.size||h.get({x:4})||h.set({x:4},"t")!=h||2!=h.size)return!1;var k=h.entries(),m=k.next();if(m.done||m.value[0]!=g||"s"!=m.value[1])return!1;m=k.next();return m.done||4!=m.value[0].x||"t"!=m.value[1]||!k.next().done?!1:!0}catch(G){return!1}}())return a;var b=new WeakMap,c=function(g){this.h={};this.g=f();
this.size=0;if(g){g=q(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}};c.prototype.set=function(g,h){g=0===g?0:g;var k=d(this,g);k.list||(k.list=this.h[k.id]=[]);k.u?k.u.value=h:(k.u={next:this.g,B:this.g.B,head:this.g,key:g,value:h},k.list.push(k.u),this.g.B.next=k.u,this.g.B=k.u,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.u&&g.list?(g.list.splice(g.index,1),g.list.length||delete this.h[g.id],g.u.B.next=g.u.next,g.u.next.B=g.u.B,g.u.head=null,this.size--,
!0):!1};c.prototype.clear=function(){this.h={};this.g=this.g.B=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).u};c.prototype.get=function(g){return(g=d(this,g).u)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,function(g){return g.value})};c.prototype.forEach=function(g,h){for(var k=this.entries(),m;!(m=k.next()).done;)m=m.value,
g.call(h,m[1],m[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,h){var k=h&&typeof h;"object"==k||"function"==k?b.has(h)?k=b.get(h):(k=""+ ++l,b.set(h,k)):k="p_"+h;var m=g.h[k];if(m&&r(g.h,k))for(g=0;g<m.length;g++){var G=m[g];if(h!==h&&G.key!==G.key||h===G.key)return{id:k,list:m,index:g,u:G}}return{id:k,list:m,index:-1,u:void 0}},e=function(g,h){var k=g.g;return da(function(){if(k){for(;k.head!=g.g;)k=k.B;for(;k.next!=k.head;)return k=k.next,{done:!1,value:h(k)};k=null}return{done:!0,
value:void 0}})},f=function(){var g={};return g.B=g.next=g.head=g},l=0;return c});var ma=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};p("Array.prototype.entries",function(a){return a?a:function(){return ma(this,function(b,c){return[b,c]})}});p("Array.prototype.keys",function(a){return a?a:function(){return ma(this,function(b){return b})}});
p("Array.prototype.values",function(a){return a?a:function(){return ma(this,function(b,c){return c})}});p("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(g){return g};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var l=0;!(f=b.next()).done;)e.push(c.call(d,f.value,l++))}else for(f=b.length,l=0;l<f;l++)e.push(c.call(d,b[l],l));return e}});
var t=this||self,u=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},na=function(a){var b=u(a);return"array"==b||"object"==b&&"number"==typeof a.length},v=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},oa=function(a,b){function c(){}c.prototype=b.prototype;a.ca=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(d,e,f){for(var l=Array(arguments.length-2),g=2;g<arguments.length;g++)l[g-2]=arguments[g];return b.prototype[e].apply(d,
l)}},pa=function(a){return a};function w(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,w);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}oa(w,Error);w.prototype.name="CustomError";function x(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");w.call(this,c+a[d])}oa(x,w);x.prototype.name="AssertionError";function y(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new x(""+e,f||[]);}
var qa=function(a,b,c){a||y("",null,b,Array.prototype.slice.call(arguments,2))},z=function(a,b){throw new x("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},A=function(a,b,c){"number"!==typeof a&&y("Expected number but got %s: %s.",[u(a),a],b,Array.prototype.slice.call(arguments,2));return a},ra=function(a,b,c){"string"!==typeof a&&y("Expected string but got %s: %s.",[u(a),a],b,Array.prototype.slice.call(arguments,2))},sa=function(a,b,c){v(a)&&1==a.nodeType||y("Expected Element but got %s: %s.",
[u(a),a],b,Array.prototype.slice.call(arguments,2));return a};var ta=Array.prototype.forEach?function(a,b){qa(null!=a.length);Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};function ua(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var Ca=function(a){if(!va.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(wa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(xa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(ya,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(za,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Aa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ba,"&#0;"));return a},wa=/&/g,xa=/</g,ya=/>/g,za=/"/g,Aa=/'/g,Ba=/\x00/g,va=/[\x00&<>"']/;function B(){var a=t.navigator;return a&&(a=a.userAgent)?a:""};try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};function Da(a,b){for(var c in a)b.call(void 0,a[c],c,a)};var Ea={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};var C;var D=function(a,b){this.g=a===Fa&&b||"";this.h=Ga};D.prototype.F=!0;D.prototype.v=function(){return this.g};D.prototype.toString=function(){return"Const{"+this.g+"}"};var Ha=function(a){if(a instanceof D&&a.constructor===D&&a.h===Ga)return a.g;z("expected object of type Const, got '"+a+"'");return"type_error:Const"},Ga={},Fa={};var E=function(a,b){this.g=b===Ia?a:""};E.prototype.toString=function(){return this.g+""};E.prototype.F=!0;E.prototype.v=function(){return this.g.toString()};var Ia={};var H=function(a,b){this.g=b===F?a:""};H.prototype.toString=function(){return this.g.toString()};H.prototype.F=!0;H.prototype.v=function(){return this.g.toString()};
var Ja=function(a){if(a instanceof H&&a.constructor===H)return a.g;z("expected object of type SafeUrl, got '"+a+"' of type "+u(a));return"type_error:SafeUrl"},Ka=/^data:(.*);base64,[a-z0-9+\/]+=*$/i,La=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,Ma=function(a){if(a instanceof H)return a;a="object"==typeof a&&a.F?a.v():String(a);La.test(a)?a=new H(a,F):(a=String(a).replace(/(%0A|%0D)/g,""),a=a.match(Ka)?new H(a,F):null);return a},F={},Na=new H("about:invalid#zClosurez",F);var Oa={},I=function(a,b){this.g=b===Oa?a:"";this.F=!0};I.prototype.v=function(){return this.g};I.prototype.toString=function(){return this.g.toString()};var Pa=new I("",Oa);function Qa(a){if(a instanceof H)return'url("'+Ja(a).replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';a=a instanceof D?Ha(a):Ra(String(a));if(/[{;}]/.test(a))throw new x("Value does not allow [{;}], got: %s.",[a]);return a}
function Ra(a){var b=a.replace(Sa,"$1").replace(Sa,"$1").replace(Ta,"url");if(Ua.test(b)){if(Va.test(a))return z("String value disallows comments, got: "+a),"zClosurez";for(var c=b=!0,d=0;d<a.length;d++){var e=a.charAt(d);"'"==e&&c?b=!b:'"'==e&&b&&(c=!c)}if(!b||!c)return z("String value requires balanced quotes, got: "+a),"zClosurez";if(!Wa(a))return z("String value requires balanced square brackets and one identifier per pair of brackets, got: "+a),"zClosurez"}else return z("String value allows only [-,.\"'%_!#/ a-zA-Z0-9\\[\\]] and simple functions, got: "+
a),"zClosurez";return Xa(a)}function Wa(a){for(var b=!0,c=/^[-_a-zA-Z0-9]$/,d=0;d<a.length;d++){var e=a.charAt(d);if("]"==e){if(b)return!1;b=!0}else if("["==e){if(!b)return!1;b=!1}else if(!b&&!c.test(e))return!1}return b}
var Ua=RegExp("^[-,.\"'%_!#/ a-zA-Z0-9\\[\\]]+$"),Ta=RegExp("\\b(url\\([ \t\n]*)('[ -&(-\\[\\]-~]*'|\"[ !#-\\[\\]-~]*\"|[!#-&*-\\[\\]-~]*)([ \t\n]*\\))","g"),Sa=RegExp("\\b(calc|cubic-bezier|fit-content|hsl|hsla|linear-gradient|matrix|minmax|radial-gradient|repeat|rgb|rgba|(rotate|scale|translate)(X|Y|Z|3d)?|var)\\([-+*/0-9a-zA-Z.%#\\[\\], ]+\\)","g"),Va=/\/\*/;
function Xa(a){return a.replace(Ta,function(b,c,d,e){var f="";d=d.replace(/^(['"])(.*)\1$/,function(l,g,h){f=g;return h});b=(Ma(d)||Na).v();return c+f+b+f+e})};var Ya={},J=function(a,b){this.g=b===Ya?a:"";this.F=!0};J.prototype.v=function(){return this.g.toString()};J.prototype.toString=function(){return this.g.toString()};
var K=function(a){if(a instanceof J&&a.constructor===J)return a.g;z("expected object of type SafeHtml, got '"+a+"' of type "+u(a));return"type_error:SafeHtml"},Za=function(a){return a instanceof J?a:L(Ca("object"==typeof a&&a.F?a.v():String(a)))},ab=function(a){var b=Za($a),c=[],d=function(e){Array.isArray(e)?e.forEach(d):(e=Za(e),c.push(K(e).toString()))};a.forEach(d);return L(c.join(K(b).toString()))},bb=function(a){return ab(Array.prototype.slice.call(arguments))},L=function(a){if(void 0===C){var b=
null;var c=t.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:pa,createScript:pa,createScriptURL:pa})}catch(d){t.console&&t.console.error(d.message)}C=b}else C=b}a=(b=C)?b.createHTML(a):a;return new J(a,Ya)},cb=/^[a-zA-Z0-9-]+$/,db={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0},eb={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0},$a=new J(t.trustedTypes&&t.trustedTypes.emptyHTML||
"",Ya),fb=L("<br>");var M=function(a){var b=document;ra(a);b="string"===typeof a?b.getElementById(a):a;return b=sa(b,"No element found with id: "+a)},hb=function(a,b){Da(b,function(c,d){c&&"object"==typeof c&&c.F&&(c=c.v());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:gb.hasOwnProperty(d)?a.setAttribute(gb[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})},gb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",
height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},jb=function(a,b,c){var d=arguments,e=document,f=d[1];var l=String(d[0]);l=String(l);"application/xhtml+xml"===e.contentType&&(l=l.toLowerCase());l=e.createElement(l);f&&("string"===typeof f?l.className=f:Array.isArray(f)?l.className=f.join(" "):hb(l,f));2<d.length&&ib(e,l,d);return l},ib=function(a,b,c){function d(g){g&&b.appendChild("string"===typeof g?a.createTextNode(g):
g)}for(var e=2;e<c.length;e++){var f=c[e];if(!na(f)||v(f)&&0<f.nodeType)d(f);else{a:{if(f&&"number"==typeof f.length){if(v(f)){var l="function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){l="function"==typeof f.item;break a}}l=!1}ta(l?ua(f):f,d)}}};var N=function(){this.h=null;this.G=!1;this.g=jb("VIDEO")};N.prototype.s=function(){};N.prototype.A=function(){};var kb=function(a,b){a.C=b};N.prototype.o=function(){};N.prototype.show=function(){this.g.style.display="block"};N.prototype.I=function(){this.g.setAttribute("controls",!0)};N.prototype.H=function(){this.g.removeAttribute("controls")};var lb=function(){this.type=this.h=null;this.g=this.j=this.l=this.i="";this.m=0};var O=function(){N.call(this);var a=this;this.g=M("hls-content")||jb("VIDEO");this.l=new Hls({autoStartLoad:!1});this.g.addEventListener("seeked",function(){if("live"!=a.j)if(a.i)a.i=!1;else{var b=a.g.currentTime,c=a.h.previousCuePointForStreamTime(b);c&&!c.played&&(a.i=!0,a.m=b,a.g.currentTime=c.start)}});this.l.on(Hls.Events.FRAG_PARSING_METADATA,function(b,c){a.h&&c&&c.samples.forEach(function(d){a.h.processMetadata("ID3",d.data,d.pts)})})};la(O,N);
O.prototype.s=function(a,b){var c=this;this.j=b;this.l.on(Hls.Events.MEDIA_ATTACHED,function(){c.l.loadSource(a);c.l.on(Hls.Events.MANIFEST_PARSED,function(){c.C()})});this.l.attachMedia(this.g)};O.prototype.A=function(a){var b=0;a&&(b=this.h.streamTimeForContentTime(a),this.i=!0);this.l.startLoad(b);this.g.setAttribute("controls",!0);this.g.play()};O.prototype.o=function(){this.g.pause();this.g.src="";this.g.style.display="none"};var P=function(){N.call(this);this.g=M("hls-content")||jb("VIDEO")};la(P,N);P.prototype.D=function(a){var b=this,c=a.track;"metadata"===c.kind&&(c.mode="hidden",c.da=function(){for(var d=q(c.activeCues),e=d.next();!e.done;e=d.next()){e=e.value;var f={};f[e.value.key]=e.value.data;b.h.onTimedMetadata(f)}})};P.prototype.l=function(){if("live"!=this.j)if(this.i)this.i=!1;else{var a=this.g.currentTime,b=this.h.previousCuePointForStreamTime(a);b&&!b.played&&(this.i=!0,this.m=a,this.g.currentTime=b.start)}};
P.prototype.s=function(a,b){var c=this;this.j=b;this.g.addEventListener("loadedmetadata",function(){c.C()});this.g.src=a;this.g.onseeked=this.l.bind(this);this.g.textTracks.onaddtrack=this.D.bind(this)};P.prototype.A=function(a){a&&(a=this.h.streamTimeForContentTime(a),this.i=!0,this.g.currentTime=a);this.g.setAttribute("controls",!0);this.g.play()};P.prototype.o=function(){this.g.src="";this.g.style.display="none"};var mb=M("play-button"),nb=!1,ob=!1,Q=function(){N.call(this);var a=this;this.g=M("dash-content")||jb("VIDEO");shaka.polyfill.installAll();this.l=new shaka.Player(this.g);this.l.addEventListener("emsg",function(b){a.h.onTimedMetadata({TXXX:b.detail.messageData})});this.l.addEventListener("timelineregionenter",function(b){a.h.onTimedMetadata({TXXX:b.detail.eventElement.attributes.messageData.nodeValue})});this.g.addEventListener("seeked",this.D.bind(this))};la(Q,N);
Q.prototype.D=function(){if("live"!=this.j)if(this.i)this.i=!1;else{var a=this.g.currentTime,b=this.h.previousCuePointForStreamTime(a);b&&!b.played&&(this.i=!0,this.m=a,this.g.currentTime=b.start)}};Q.prototype.s=function(a,b){var c=this;this.j=b;"live"==this.j?this.H():this.I();this.l.load(a).then(function(){c.C()})};
Q.prototype.A=function(a){if(nb&&"live"==this.j)ob?(this.g.pause(),mb.textContent="Play",ob=!1):(this.g.play(),mb.textContent="Pause",ob=!0);else{var b=0;nb=!0;a&&(b=this.h.streamTimeForContentTime(a),this.i=!0);this.g.currentTime=b;this.g.play();"live"==this.j&&(mb.textContent="Pause",ob=!0)}};Q.prototype.o=function(){this.l.unload();this.g.style.display="none"};Q.prototype.I=function(){"live"!=this.j&&this.g.setAttribute("controls",!0)};Q.prototype.H=function(){this.g.removeAttribute("controls")};var pb=function(){this.i=this.l=this.g=this.j=this.h=null},qb=function(a,b){a.l=b},rb=function(a){a.i=new google.ima.dai.api.StreamManager(a.h.g,a.j);a.i.addEventListener([google.ima.dai.api.StreamEvent.Type.AD_BREAK_ENDED,google.ima.dai.api.StreamEvent.Type.AD_BREAK_STARTED,google.ima.dai.api.StreamEvent.Type.AD_PROGRESS,google.ima.dai.api.StreamEvent.Type.CLICK,google.ima.dai.api.StreamEvent.Type.COMPLETE,google.ima.dai.api.StreamEvent.Type.CUEPOINTS_CHANGED,google.ima.dai.api.StreamEvent.Type.ERROR,
google.ima.dai.api.StreamEvent.Type.FIRST_QUARTILE,google.ima.dai.api.StreamEvent.Type.LOADED,google.ima.dai.api.StreamEvent.Type.MIDPOINT,google.ima.dai.api.StreamEvent.Type.STARTED,google.ima.dai.api.StreamEvent.Type.STREAM_INITIALIZED,google.ima.dai.api.StreamEvent.Type.THIRD_QUARTILE],function(b){switch(b.type){case google.ima.dai.api.StreamEvent.Type.LOADED:a.h.s(b.getStreamData().url,a.g.type);break;case google.ima.dai.api.StreamEvent.Type.ERROR:a.h.s("http://storage.googleapis.com/testtopbox-public/video_content/bbb/master.m3u8",
"vod");break;case google.ima.dai.api.StreamEvent.Type.AD_BREAK_STARTED:var c=a.h;c.G=!0;c.H();break;case google.ima.dai.api.StreamEvent.Type.AD_BREAK_ENDED:c=a.h,c.G=!1,c.I(),c.m&&c.m>c.g.currentTime&&(c.g.currentTime=c.m,c.m=null)}a.l(b)})},sb=function(a,b,c){a.h=b;a.g=c;a.i?a.i.reset():rb(a);a.h.h=a.i;"live"==a.g.type?(b=new google.ima.dai.api.LiveStreamRequest,b.format=a.g.h,b.assetKey=a.g.i,b.apiKey=a.g.g):(b=new google.ima.dai.api.VODStreamRequest,b.format=a.g.h,b.contentSourceId=a.g.l,b.videoId=
a.g.j,b.apiKey=a.g.g);a.i.requestStream(b)};var tb=function(a,b){this.name=a;this.value=b};tb.prototype.toString=function(){return this.name};
var ub=new tb("OFF",Infinity),vb=new tb("WARNING",900),wb=new tb("CONFIG",700),xb=function(){},yb,zb=function(){},Ab=function(a,b){this.g=null;this.j=[];this.h=(void 0===b?null:b)||null;this.i=[];this.l={g:function(){return a}}},Bb=function(a){if(a.g)return a.g;if(a.h)return Bb(a.h);z("Root logger has no level set.");return ub},Cb=function(a,b){for(;a;)a.j.forEach(function(c){c(b)}),a=a.h},Db=function(){this.entries={};var a=new Ab("");a.g=wb;this.entries[""]=a},Eb,Fb=function(a,b){var c=a.entries[b];
if(c)return c;c=Fb(a,b.slice(0,Math.max(b.lastIndexOf("."),0)));var d=new Ab(b,c);a.entries[b]=d;c.i.push(d);return d},Gb=function(){Eb||(Eb=new Db);return Eb};/*

 SPDX-License-Identifier: Apache-2.0
*/
var Hb=[],Ib=function(a){var b;if(b=Fb(Gb(),"safevalues").l){a="A URL with content '"+a+"' was sanitized away.";var c;if(c=b)if(c=b&&vb){c=vb.value;var d=b?Bb(Fb(Gb(),b.g())):ub;c=c>=d.value}c&&(b=Fb(Gb(),b.g()),"function"===typeof a&&a(),yb||(yb=new xb),a=new zb,Cb(b,a))}};-1===Hb.indexOf(Ib)&&Hb.push(Ib);var Jb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),Kb=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var R=function(a){this.i=this.o=this.j="";this.s=null;this.m=this.h="";this.l=!1;var b;a instanceof R?(this.l=a.l,Lb(this,a.j),this.o=a.o,this.i=a.i,Mb(this,a.s),this.h=a.h,Nb(this,Ob(a.g)),this.m=a.m):a&&(b=String(a).match(Jb))?(this.l=!1,Lb(this,b[1]||"",!0),this.o=S(b[2]||""),this.i=S(b[3]||"",!0),Mb(this,b[4]),this.h=S(b[5]||"",!0),Nb(this,b[6]||"",!0),this.m=S(b[7]||"")):(this.l=!1,this.g=new T(null,this.l))};
R.prototype.toString=function(){var a=[],b=this.j;b&&a.push(U(b,Pb,!0),":");var c=this.i;if(c||"file"==b)a.push("//"),(b=this.o)&&a.push(U(b,Pb,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.s,null!=c&&a.push(":",String(c));if(c=this.h)this.i&&"/"!=c.charAt(0)&&a.push("/"),a.push(U(c,"/"==c.charAt(0)?Qb:Rb,!0));(c=this.g.toString())&&a.push("?",c);(c=this.m)&&a.push("#",U(c,Sb));return a.join("")};
R.prototype.resolve=function(a){var b=new R(this),c=!!a.j;c?Lb(b,a.j):c=!!a.o;c?b.o=a.o:c=!!a.i;c?b.i=a.i:c=null!=a.s;var d=a.h;if(c)Mb(b,a.s);else if(c=!!a.h){if("/"!=d.charAt(0))if(this.i&&!this.h)d="/"+d;else{var e=b.h.lastIndexOf("/");-1!=e&&(d=b.h.slice(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],l=0;l<e.length;){var g=e[l++];"."==g?d&&l==e.length&&f.push(""):".."==g?((1<f.length||1==f.length&&""!=
f[0])&&f.pop(),d&&l==e.length&&f.push("")):(f.push(g),d=!0)}d=f.join("/")}else d=e}c?b.h=d:c=""!==a.g.toString();c?Nb(b,Ob(a.g)):c=!!a.m;c&&(b.m=a.m);return b};
var Lb=function(a,b,c){a.j=c?S(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))},Mb=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.s=b}else a.s=null},Nb=function(a,b,c){b instanceof T?(a.g=b,Tb(a.g,a.l)):(c||(b=U(b,Ub)),a.g=new T(b,a.l))},S=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},U=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Vb),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Vb=function(a){a=
a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Pb=/[#\/\?@]/g,Rb=/[#\?:]/g,Qb=/[#\?]/g,Ub=/[#\?@]/g,Sb=/#/g,T=function(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b},V=function(a){a.g||(a.g=new Map,a.h=0,a.i&&Kb(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};T.prototype.add=function(a,b){V(this);this.i=null;a=W(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h=A(this.h)+1;return this};
var Wb=function(a,b){V(a);b=W(a,b);a.g.has(b)&&(a.i=null,a.h=A(a.h)-a.g.get(b).length,a.g.delete(b))},Xb=function(a,b){V(a);b=W(a,b);return a.g.has(b)};T.prototype.forEach=function(a,b){V(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};var Yb=function(a,b){V(a);var c=[];if("string"===typeof b)Xb(a,b)&&(c=c.concat(a.g.get(W(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c};
T.prototype.set=function(a,b){V(this);this.i=null;a=W(this,a);Xb(this,a)&&(this.h=A(this.h)-this.g.get(a).length);this.g.set(a,[b]);this.h=A(this.h)+1;return this};T.prototype.get=function(a,b){if(!a)return b;a=Yb(this,a);return 0<a.length?String(a[0]):b};
T.prototype.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=Yb(this,d);for(var f=0;f<d.length;f++){var l=e;""!==d[f]&&(l+="="+encodeURIComponent(String(d[f])));a.push(l)}}return this.i=a.join("&")};
var Ob=function(a){var b=new T;b.i=a.i;a.g&&(b.g=new Map(a.g),b.h=a.h);return b},W=function(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b},Tb=function(a,b){b&&!a.j&&(V(a),a.i=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Wb(this,d),Wb(this,e),0<c.length&&(this.i=null,this.g.set(W(this,e),ua(c)),this.h=A(this.h)+c.length))},a));a.j=b};var cc=function(a){var b=this;this.O=new pb;this.h=Zb(this);this.g=Zb(this);this.A=M("live-radio");this.X=M("sample-live-link");this.T=M("live-inputs");this.V=M("vod-inputs");this.K=M("vod-radio");this.ba=M("sample-vod-link");this.s=M("asset-key");this.S=M("live-api-key");this.l=M("cms-id");this.o=M("video-id");this.U=M("vod-api-key");this.aa=M("stream-formats");this.m=M("hls-radio");this.L=M("dash-radio");this.i=M("ad-ui");this.Y=M("load-button");this.N=M("play-button");this.D=M("bookmark-button");
this.P=M("bookmark-wrapper");this.W=M("bookmark-link-text");this.J=M("console");this.M=a;this.Z=$b(this);this.C=[];ac(this,this.M);this.O.j=this.i;qb(this.O,function(c){c.type!=google.ima.dai.api.StreamEvent.Type.AD_PROGRESS&&b.log("Stream event: "+c.type);switch(c.type){case google.ima.dai.api.StreamEvent.Type.ERROR:b.log("Stream error: "+c.getStreamData().errorMessage);break;case google.ima.dai.api.StreamEvent.Type.LOADED:b.log("Stream ID: "+c.getStreamData().streamId);break;case google.ima.dai.api.StreamEvent.Type.AD_BREAK_STARTED:b.i.style.display=
"block";break;case google.ima.dai.api.StreamEvent.Type.AD_BREAK_ENDED:b.i.style.display="none"}});bc(this)},ac=function(a,b){if(b){var c=new R(b);b=c.g.get("streamType");var d=c.g.get("streamFormat"),e=c.g.get("assetKey"),f=c.g.get("apiKey"),l=c.g.get("cmsId");c=c.g.get("videoId");b&&("live"===b.toLowerCase()?(a.K.checked=!1,a.A.checked=!0,dc(a),f&&(a.S.value=f)):"vod"===b.toLowerCase()&&(a.K.checked=!0,a.A.checked=!1,ec(a),f&&(a.U.value=f)));d&&("hls"===d.toLowerCase()?(a.L.checked=!1,a.m.checked=
!0,fc(a)):"dash"===d.toLowerCase()&&(a.L.checked=!0,a.m.checked=!1,gc(a)));e&&(a.s.value=e);l&&(a.l.value=l);c&&(a.o.value=c)}},Zb=function(a){if(!a.h){-1!=B().indexOf("iPhone")&&-1==B().indexOf("iPod")&&-1==B().indexOf("iPad")||-1!=B().indexOf("iPad")||-1!=B().indexOf("iPod")?a.h=new P:a.h=new O;var b=a.h.g;b.addEventListener("pause",function(){var c=a.h;c.G&&(c.I(),a.i.style.display="none")});b.addEventListener("play",function(){var c=a.h;c.G&&(c.H(),a.i.style.display="block")})}return a.h},hc=
function(a){if(!a.j){a.j=new Q;var b=a.j.g;b.addEventListener("pause",function(){var c=a.j;c.G&&(c.I(),a.i.style.display="none")});b.addEventListener("play",function(){var c=a.j;c.G&&(c.H(),a.i.style.display="block")})}return a.j},$b=function(a){var b={};a=a.M.split("?")[1];if(!a)return b;a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");b[d[0]]=decodeURIComponent(d[1])}return b},bc=function(a){a.A.addEventListener("click",function(){return dc(a)});a.K.addEventListener("click",function(){return ec(a)});
a.X.addEventListener("click",function(){return ic(a)});a.ba.addEventListener("click",function(){return jc(a)});a.m.addEventListener("click",function(){return fc(a)});a.L.addEventListener("click",function(){return gc(a)});a.Y.addEventListener("click",function(){return kc(a)});a.N.addEventListener("click",function(){a.g.A(lc(a))});a.D.addEventListener("click",function(){if(a.g.g.currentTime){var b=a.g;b=Math.floor(b.h.contentTimeForStreamTime(b.g.currentTime));b=a.M.split("?")[0]+"?bookmark="+b}else b=
"Error: could not get current time of video element, or current time is 0";a.W.value=b;a.P.style.display="block"});a.aa.style.display="block"},dc=function(a){a.V.style.display="none";a.T.style.display="block";mc(a)},ec=function(a){a.T.style.display="none";a.V.style.display="block";mc(a)},mc=function(a){a.i.style.display="none";a.N.setAttribute("disabled",!0);a.D.setAttribute("disabled",!0)},ic=function(a){a.s.value=a.m.checked?"c-rArva4ShKVIAkNfy6HUQ":"PSzZMzAkSXCmlJOWDmRj8Q";dc(a)},jc=function(a){a.m.checked?
(a.l.value="2548831",a.o.value="tears-of-steel"):(a.l.value="2559737",a.o.value="tos-dash");ec(a)},fc=function(a){a.A.removeAttribute("disabled");a.j&&a.j.o();mc(a);a.K.checked&&"2559737"==a.l.value&&"tos-dash"==a.o.value?jc(a):"PSzZMzAkSXCmlJOWDmRj8Q"==a.s.value&&ic(a);a.g=Zb(a);a.g.show()},gc=function(a){a.h.o();mc(a);"2548831"==a.l.value&&"tears-of-steel"==a.o.value?jc(a):"c-rArva4ShKVIAkNfy6HUQ"==a.s.value&&ic(a);a.g=hc(a);a.g.show()},kc=function(a){a.R=nc(a);kb(a.g,function(){"live"==a.R.type?
(a.D.setAttribute("disabled",!0),a.P.style.display="none"):a.D.removeAttribute("disabled");a.N.removeAttribute("disabled")});sb(a.O,a.g,a.R);oc(a)},nc=function(a){var b=new lb;b.h=a.m.checked?"hls":"dash";a.A.checked?(b.type="live",b.i=a.s.value,b.g=a.S.value):(b.type="vod",b.l=a.l.value,b.j=a.o.value,b.g=a.U.value,b.m=lc(a));return b},lc=function(a){a=parseInt(a.Z.bookmark,10);return isNaN(a)?0:a},oc=function(a){a.C.length=0;a.J.textContent=""};
cc.prototype.log=function(a){if(!cb.test("span"))throw Error("Invalid tag name <span>.");if("SPAN"in eb)throw Error("Tag name <span> is not allowed for SafeHtml.");var b={},c="";if(b)for(h in b)if(Object.prototype.hasOwnProperty.call(b,h)){if(!cb.test(h))throw Error('Invalid attribute name "'+h+'".');var d=b[h];if(null!=d){var e=void 0;var f=h;if(d instanceof D)d=Ha(d);else if("style"==f.toLowerCase()){if(!v(d))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+
typeof d+" given: "+d);if(!(d instanceof I)){var l="";for(e in d)if(Object.prototype.hasOwnProperty.call(d,e)){if(!/^[-_a-zA-Z0-9]+$/.test(e))throw Error("Name allows only [-_a-zA-Z0-9], got: "+e);var g=d[e];null!=g&&(g=Array.isArray(g)?g.map(Qa).join(" "):Qa(g),l+=e+":"+g+";")}d=l?new I(l,Oa):Pa}d instanceof I&&d.constructor===I?d=d.g:(z("expected object of type SafeStyle, got '"+d+"' of type "+u(d)),d="type_error:SafeStyle")}else{if(/^on/i.test(f))throw Error('Attribute "'+f+'" requires goog.string.Const value, "'+
d+'" given.');if(f.toLowerCase()in db)if(d instanceof E)d instanceof E&&d.constructor===E?e=d.g:(z("expected object of type TrustedResourceUrl, got '"+d+"' of type "+u(d)),e="type_error:TrustedResourceUrl"),d=e.toString();else if(d instanceof H)d=Ja(d);else if("string"===typeof d)d=(Ma(d)||Na).v();else throw Error('Attribute "'+f+'" on tag "span" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+d+'" given.');}d.F&&(d=d.v());qa("string"===typeof d||"number"===typeof d,"String or number value expected, got "+
typeof d+" with value: "+d);f=f+'="'+Ca(String(d))+'"';c+=" "+f}}var h="<span"+c;null==a?a=[]:Array.isArray(a)||(a=[a]);!0===Ea.span?(qa(!a.length,"Void tag <span> does not allow content."),h+=">"):(a=bb(a),h+=">"+K(a).toString()+"</span>");a=L(h);0==this.C.length?this.C.push(a):this.C.push(bb(fb,a));a=this.J;h=bb.apply;b=this.C;if(!(b instanceof Array)){b=q(b);for(f=[];!(c=b.next()).done;)f.push(c.value);b=f}h=h.call(bb,J,b);if(void 0!==a.tagName){if("script"===a.tagName.toLowerCase())throw Error("Use setTextContent with a SafeScript.");
if("style"===a.tagName.toLowerCase())throw Error("Use setTextContent with a SafeStyleSheet.");}a.innerHTML=K(h);this.J.scrollTop=this.J.scrollHeight};var X=["Controller"],Y=t;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===cc?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=cc;}).call(this);
})();