(function(){(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},m=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");},ba="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,
c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a},ca=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},da=ca(this),q=function(a,b){if(b)a:{var c=da;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=
d&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}},r;if("function"==typeof Object.setPrototypeOf)r=Object.setPrototypeOf;else{var t;a:{var ea={a:!0},fa={};try{fa.__proto__=ea;t=fa.a;break a}catch(a){}t=!1}r=t?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var ha=r,u=function(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ma=b.prototype};
q("Symbol",function(a){if(a)return a;var b=function(f,l){this.g=f;p(this,"description",{configurable:!0,writable:!0,value:l})};b.prototype.toString=function(){return this.g};var c="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",d=0,e=function(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b(c+(f||"")+"_"+d++,f)};return e});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&p(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ia(aa(this))}})}return a});
var ia=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a},v=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
q("WeakMap",function(a){function b(){}function c(h){var k=typeof h;return"object"===k&&null!==h||"function"===k}function d(h){if(!v(h,f)){var k=new b;p(h,f,{value:k})}}function e(h){var k=Object[h];k&&(Object[h]=function(n){if(n instanceof b)return n;Object.isExtensible(n)&&d(n);return k(n)})}if(function(){if(!a||!Object.seal)return!1;try{var h=Object.seal({}),k=Object.seal({}),n=new a([[h,2],[k,3]]);if(2!=n.get(h)||3!=n.get(k))return!1;n.delete(h);n.set(k,4);return!n.has(h)&&4==n.get(k)}catch(z){return!1}}())return a;
var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var l=0,g=function(h){this.g=(l+=Math.random()+1).toString();if(h){h=m(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}};g.prototype.set=function(h,k){if(!c(h))throw Error("Invalid WeakMap key");d(h);if(!v(h,f))throw Error("WeakMap key fail: "+h);h[f][this.g]=k;return this};g.prototype.get=function(h){return c(h)&&v(h,f)?h[f][this.g]:void 0};g.prototype.has=function(h){return c(h)&&v(h,f)&&v(h[f],this.g)};
g.prototype.delete=function(h){return c(h)&&v(h,f)&&v(h[f],this.g)?delete h[f][this.g]:!1};return g});
q("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),h=new a(m([[g,"s"]]));if("s"!=h.get(g)||1!=h.size||h.get({x:4})||h.set({x:4},"t")!=h||2!=h.size)return!1;var k=h.entries(),n=k.next();if(n.done||n.value[0]!=g||"s"!=n.value[1])return!1;n=k.next();return n.done||4!=n.value[0].x||"t"!=n.value[1]||!k.next().done?!1:!0}catch(z){return!1}}())return a;var b=new WeakMap,c=function(g){this[0]={};this[1]=
f();this.size=0;if(g){g=m(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}};c.prototype.set=function(g,h){g=0===g?0:g;var k=d(this,g);k.list||(k.list=this[0][k.id]=[]);k.u?k.u.value=h:(k.u={next:this[1],B:this[1].B,head:this[1],key:g,value:h},k.list.push(k.u),this[1].B.next=k.u,this[1].B=k.u,this.size++);return this};c.prototype.delete=function(g){g=d(this,g);return g.u&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.u.B.next=g.u.next,g.u.next.B=g.u.B,g.u.head=
null,this.size--,!0):!1};c.prototype.clear=function(){this[0]={};this[1]=this[1].B=f();this.size=0};c.prototype.has=function(g){return!!d(this,g).u};c.prototype.get=function(g){return(g=d(this,g).u)&&g.value};c.prototype.entries=function(){return e(this,function(g){return[g.key,g.value]})};c.prototype.keys=function(){return e(this,function(g){return g.key})};c.prototype.values=function(){return e(this,function(g){return g.value})};c.prototype.forEach=function(g,h){for(var k=this.entries(),n;!(n=k.next()).done;)n=
n.value,g.call(h,n[1],n[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var d=function(g,h){var k=h&&typeof h;"object"==k||"function"==k?b.has(h)?k=b.get(h):(k=""+ ++l,b.set(h,k)):k="p_"+h;var n=g[0][k];if(n&&v(g[0],k))for(g=0;g<n.length;g++){var z=n[g];if(h!==h&&z.key!==z.key||h===z.key)return{id:k,list:n,index:g,u:z}}return{id:k,list:n,index:-1,u:void 0}},e=function(g,h){var k=g[1];return ia(function(){if(k){for(;k.head!=g[1];)k=k.B;for(;k.next!=k.head;)return k=k.next,{done:!1,value:h(k)};
k=null}return{done:!0,value:void 0}})},f=function(){var g={};return g.B=g.next=g.head=g},l=0;return c});var ja=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};q("Array.prototype.values",function(a){return a?a:function(){return ja(this,function(b,c){return c})}});
q("Array.prototype.keys",function(a){return a?a:function(){return ja(this,function(b){return b})}});q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(g){return g};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var l=0;!(f=b.next()).done;)e.push(c.call(d,f.value,l++))}else for(f=b.length,l=0;l<f;l++)e.push(c.call(d,b[l],l));return e}});
q("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});q("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
q("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(b,c||0)}});
var w=this||self,x=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},ka=function(a){var b=x(a);return"array"==b||"object"==b&&"number"==typeof a.length},la=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},ma=function(a,b){function c(){}c.prototype=b.prototype;a.ma=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(d,e,f){for(var l=Array(arguments.length-2),g=2;g<arguments.length;g++)l[g-2]=arguments[g];return b.prototype[e].apply(d,
l)}};function y(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,y);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}ma(y,Error);y.prototype.name="CustomError";function A(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");y.call(this,c+a[d])}ma(A,y);A.prototype.name="AssertionError";function B(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new A(""+e,f||[]);}
var na=function(a,b,c){a||B("",null,b,Array.prototype.slice.call(arguments,2));return a},C=function(a,b,c){"number"!==typeof a&&B("Expected number but got %s: %s.",[x(a),a],b,Array.prototype.slice.call(arguments,2));return a},oa=function(a,b,c){"string"!==typeof a&&B("Expected string but got %s: %s.",[x(a),a],b,Array.prototype.slice.call(arguments,2))};var pa=Array.prototype.forEach?function(a,b){na(null!=a.length);Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)};function qa(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function D(){var a=w.navigator;return a&&(a=a.userAgent)?a:""};try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};function ra(a,b){for(var c in a)b.call(void 0,a[c],c,a)};var E=function(a){if(sa!==sa)throw Error("SafeUrl is not meant to be built directly");this.g=a};E.prototype.toString=function(){return this.g.toString()};E.prototype.L=!0;E.prototype.K=function(){return this.g.toString()};var sa={};new E("about:invalid#zClosurez");new E("about:blank");var ta={},F=function(){if(ta!==ta)throw Error("SafeStyle is not meant to be built directly");this.L=!0};F.prototype.K=function(){return""};F.prototype.toString=function(){return"".toString()};new F;var ua={},G=function(){if(ua!==ua)throw Error("SafeStyleSheet is not meant to be built directly");this.L=!0};G.prototype.toString=function(){return"".toString()};G.prototype.K=function(){return""};new G;var va={},H=function(){var a=w.trustedTypes&&w.trustedTypes.emptyHTML||"";if(va!==va)throw Error("SafeHtml is not meant to be built directly");this.g=a;this.L=!0};H.prototype.K=function(){return this.g.toString()};H.prototype.toString=function(){return this.g.toString()};new H;var I=function(a){var b=document;oa(a);b="string"===typeof a?b.getElementById(a):a;return na(b,"No element found with id: "+a)},xa=function(a,b){ra(b,function(c,d){c&&"object"==typeof c&&c.L&&(c=c.K());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:wa.hasOwnProperty(d)?a.setAttribute(wa[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})},wa={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",
height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},J=function(a,b,c){var d=arguments,e=document,f=d[1];var l=String(d[0]);l=String(l);"application/xhtml+xml"===e.contentType&&(l=l.toLowerCase());l=e.createElement(l);f&&("string"===typeof f?l.className=f:Array.isArray(f)?l.className=f.join(" "):xa(l,f));2<d.length&&ya(e,l,d);return l},ya=function(a,b,c){function d(g){g&&b.appendChild("string"===typeof g?a.createTextNode(g):
g)}for(var e=2;e<c.length;e++){var f=c[e];if(!ka(f)||la(f)&&0<f.nodeType)d(f);else{a:{if(f&&"number"==typeof f.length){if(la(f)){var l="function"==typeof f.item||"string"==typeof f.item;break a}if("function"===typeof f){l="function"==typeof f.item;break a}}l=!1}pa(l?qa(f):f,d)}}};var K=function(){this.h=null;this.D=!1;this.g=J("VIDEO")};K.prototype.s=function(){};K.prototype.v=function(){};var za=function(a,b){a.C=b};K.prototype.o=function(){};K.prototype.show=function(){this.g.style.display="block"};K.prototype.H=function(){this.g.setAttribute("controls",!0)};K.prototype.G=function(){this.g.removeAttribute("controls")};var Aa=function(){this.type=this.i=null;this.g=this.m=this.o=this.j="";this.s=0;this.h={}};var L=function(){K.call(this);var a=this;this.g=I("hls-content")||J("VIDEO");this.l=new Hls({autoStartLoad:!1});this.g.addEventListener("seeked",function(){if("live"!=a.j)if(a.i)a.i=!1;else{var b=a.g.currentTime,c=a.h.previousCuePointForStreamTime(b);c&&!c.played&&(a.i=!0,a.m=b,a.g.currentTime=c.start)}});this.l.on(Hls.Events.FRAG_PARSING_METADATA,function(b,c){a.h&&c&&c.samples.forEach(function(d){a.h.processMetadata("ID3",d.data,d.pts)})})};u(L,K);
L.prototype.s=function(a,b){var c=this;this.j=b;this.l.on(Hls.Events.MEDIA_ATTACHED,function(){c.l.loadSource(a);c.l.on(Hls.Events.MANIFEST_PARSED,function(){c.C()})});this.l.attachMedia(this.g)};L.prototype.v=function(a){var b=0;a&&(b=this.h.streamTimeForContentTime(a),this.i=!0);this.l.startLoad(b);this.g.setAttribute("controls",!0);this.g.play()};L.prototype.o=function(){this.g.pause();this.g.src="";this.g.style.display="none"};var M=function(){K.call(this);this.g=I("hls-content")||J("VIDEO")};u(M,K);M.prototype.A=function(a){var b=this,c=a.track;"metadata"===c.kind&&(c.mode="hidden",c.na=function(){for(var d=m(c.activeCues),e=d.next();!e.done;e=d.next()){e=e.value;var f={};f[e.value.key]=e.value.data;b.h.onTimedMetadata(f)}})};M.prototype.l=function(){if("live"!=this.j)if(this.i)this.i=!1;else{var a=this.g.currentTime,b=this.h.previousCuePointForStreamTime(a);b&&!b.played&&(this.i=!0,this.m=a,this.g.currentTime=b.start)}};
M.prototype.s=function(a,b){var c=this;this.j=b;this.g.addEventListener("loadedmetadata",function(){c.C()});this.g.src=a;this.g.onseeked=this.l.bind(this);this.g.textTracks.onaddtrack=this.A.bind(this)};M.prototype.v=function(a){a&&(a=this.h.streamTimeForContentTime(a),this.i=!0,this.g.currentTime=a);this.g.setAttribute("controls",!0);this.g.play()};M.prototype.o=function(){this.g.src="";this.g.style.display="none"};var Ba=I("play-button"),Ca=!1,N=!1,O=function(){K.call(this);var a=this;this.g=I("dash-content")||J("VIDEO");shaka.polyfill.installAll();this.l=new shaka.Player(this.g);this.l.addEventListener("emsg",function(b){a.h.onTimedMetadata({TXXX:b.detail.messageData})});this.l.addEventListener("timelineregionenter",function(b){a.h.onTimedMetadata({TXXX:b.detail.eventElement.attributes.messageData.nodeValue})});this.g.addEventListener("seeked",this.A.bind(this))};u(O,K);
O.prototype.A=function(){if("live"!=this.j)if(this.i)this.i=!1;else{var a=this.g.currentTime,b=this.h.previousCuePointForStreamTime(a);b&&!b.played&&(this.i=!0,this.m=a,this.g.currentTime=b.start)}};O.prototype.s=function(a,b){var c=this;this.j=b;"live"==this.j?this.G():this.H();this.l.load(a).then(function(){c.C()}).catch(function(d){console.log("Shaka Player error: "+d.code,d)})};
O.prototype.v=function(a){if(Ca&&"live"==this.j)N?(this.g.pause(),Ba.textContent="Play",N=!1):(this.g.play(),Ba.textContent="Pause",N=!0);else{var b=0;Ca=!0;a&&(b=this.h.streamTimeForContentTime(a),this.i=!0);this.g.currentTime=b;this.g.play();"live"==this.j&&(Ba.textContent="Pause",N=!0)}};O.prototype.o=function(){this.l.unload();this.g.style.display="none"};O.prototype.H=function(){"live"!=this.j&&this.g.setAttribute("controls",!0)};O.prototype.G=function(){this.g.removeAttribute("controls")};var Da=function(){this.i=this.l=this.g=this.j=this.h=null},Ea=function(a,b){a.l=b},Fa=function(a){a.i=new google.ima.dai.api.StreamManager(a.h.g,a.j);a.i.addEventListener([google.ima.dai.api.StreamEvent.Type.AD_BREAK_ENDED,google.ima.dai.api.StreamEvent.Type.AD_BREAK_STARTED,google.ima.dai.api.StreamEvent.Type.AD_PROGRESS,google.ima.dai.api.StreamEvent.Type.CLICK,google.ima.dai.api.StreamEvent.Type.COMPLETE,google.ima.dai.api.StreamEvent.Type.CUEPOINTS_CHANGED,google.ima.dai.api.StreamEvent.Type.ERROR,
google.ima.dai.api.StreamEvent.Type.FIRST_QUARTILE,google.ima.dai.api.StreamEvent.Type.LOADED,google.ima.dai.api.StreamEvent.Type.MIDPOINT,google.ima.dai.api.StreamEvent.Type.STARTED,google.ima.dai.api.StreamEvent.Type.STREAM_INITIALIZED,google.ima.dai.api.StreamEvent.Type.THIRD_QUARTILE],function(b){switch(b.type){case google.ima.dai.api.StreamEvent.Type.LOADED:a.h.s(b.getStreamData().url,a.g.type);break;case google.ima.dai.api.StreamEvent.Type.ERROR:a.h.s("http://storage.googleapis.com/testtopbox-public/video_content/bbb/master.m3u8",
"vod");break;case google.ima.dai.api.StreamEvent.Type.AD_BREAK_STARTED:var c=a.h;c.D=!0;c.G();break;case google.ima.dai.api.StreamEvent.Type.AD_BREAK_ENDED:c=a.h,c.D=!1,c.H(),c.m&&c.m>c.g.currentTime&&(c.g.currentTime=c.m,c.m=null)}a.l(b)})},Ga=function(a,b,c){a.h=b;a.g=c;a.i?a.i.reset():Fa(a);a.h.h=a.i;"live"==a.g.type?(b=new google.ima.dai.api.LiveStreamRequest,b.format=a.g.i,b.assetKey=a.g.j,b.apiKey=a.g.g,b.adTagParameters=a.g.h,b.omidAccessModeRules=a.g.l):(b=new google.ima.dai.api.VODStreamRequest,
b.format=a.g.i,b.contentSourceId=a.g.o,b.videoId=a.g.m,b.apiKey=a.g.g,b.adTagParameters=a.g.h,b.omidAccessModeRules=a.g.l);a.i.requestStream(b)};var Ha=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$"),Ia=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var P=function(a){this.i=this.o=this.j="";this.s=null;this.m=this.h="";this.l=!1;var b;a instanceof P?(this.l=a.l,Ja(this,a.j),this.o=a.o,this.i=a.i,Ka(this,a.s),this.h=a.h,La(this,Ma(a.g)),this.m=a.m):a&&(b=String(a).match(Ha))?(this.l=!1,Ja(this,b[1]||"",!0),this.o=Q(b[2]||""),this.i=Q(b[3]||"",!0),Ka(this,b[4]),this.h=Q(b[5]||"",!0),La(this,b[6]||"",!0),this.m=Q(b[7]||"")):(this.l=!1,this.g=new R(null,this.l))};
P.prototype.toString=function(){var a=[],b=this.j;b&&a.push(S(b,Na,!0),":");var c=this.i;if(c||"file"==b)a.push("//"),(b=this.o)&&a.push(S(b,Na,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.s,null!=c&&a.push(":",String(c));if(c=this.h)this.i&&"/"!=c.charAt(0)&&a.push("/"),a.push(S(c,"/"==c.charAt(0)?Oa:Pa,!0));(c=this.g.toString())&&a.push("?",c);(c=this.m)&&a.push("#",S(c,Qa));return a.join("")};
P.prototype.resolve=function(a){var b=new P(this),c=!!a.j;c?Ja(b,a.j):c=!!a.o;c?b.o=a.o:c=!!a.i;c?b.i=a.i:c=null!=a.s;var d=a.h;if(c)Ka(b,a.s);else if(c=!!a.h){if("/"!=d.charAt(0))if(this.i&&!this.h)d="/"+d;else{var e=b.h.lastIndexOf("/");-1!=e&&(d=b.h.slice(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],l=0;l<e.length;){var g=e[l++];"."==g?d&&l==e.length&&f.push(""):".."==g?((1<f.length||1==f.length&&""!=
f[0])&&f.pop(),d&&l==e.length&&f.push("")):(f.push(g),d=!0)}d=f.join("/")}else d=e}c?b.h=d:c=""!==a.g.toString();c?La(b,Ma(a.g)):c=!!a.m;c&&(b.m=a.m);return b};
var Ja=function(a,b,c){a.j=c?Q(b,!0):b;a.j&&(a.j=a.j.replace(/:$/,""))},Ka=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.s=b}else a.s=null},La=function(a,b,c){b instanceof R?(a.g=b,Ra(a.g,a.l)):(c||(b=S(b,Sa)),a.g=new R(b,a.l))},Q=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},S=function(a,b,c){return"string"===typeof a?(a=encodeURI(a).replace(b,Ta),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Ta=function(a){a=
a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Na=/[#\/\?@]/g,Pa=/[#\?:]/g,Oa=/[#\?]/g,Sa=/[#\?@]/g,Qa=/#/g,R=function(a,b){this.h=this.g=null;this.i=a||null;this.j=!!b},T=function(a){a.g||(a.g=new Map,a.h=0,a.i&&Ia(a.i,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)}))};R.prototype.add=function(a,b){T(this);this.i=null;a=U(this,a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.h=C(this.h)+1;return this};
var Ua=function(a,b){T(a);b=U(a,b);a.g.has(b)&&(a.i=null,a.h=C(a.h)-a.g.get(b).length,a.g.delete(b))},Va=function(a,b){T(a);b=U(a,b);return a.g.has(b)};R.prototype.forEach=function(a,b){T(this);this.g.forEach(function(c,d){c.forEach(function(e){a.call(b,e,d,this)},this)},this)};var Wa=function(a,b){T(a);var c=[];if("string"===typeof b)Va(a,b)&&(c=c.concat(a.g.get(U(a,b))));else for(a=Array.from(a.g.values()),b=0;b<a.length;b++)c=c.concat(a[b]);return c};
R.prototype.set=function(a,b){T(this);this.i=null;a=U(this,a);Va(this,a)&&(this.h=C(this.h)-this.g.get(a).length);this.g.set(a,[b]);this.h=C(this.h)+1;return this};R.prototype.get=function(a,b){if(!a)return b;a=Wa(this,a);return 0<a.length?String(a[0]):b};
R.prototype.toString=function(){if(this.i)return this.i;if(!this.g)return"";for(var a=[],b=Array.from(this.g.keys()),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=Wa(this,d);for(var f=0;f<d.length;f++){var l=e;""!==d[f]&&(l+="="+encodeURIComponent(String(d[f])));a.push(l)}}return this.i=a.join("&")};
var Ma=function(a){var b=new R;b.i=a.i;a.g&&(b.g=new Map(a.g),b.h=a.h);return b},U=function(a,b){b=String(b);a.j&&(b=b.toLowerCase());return b},Ra=function(a,b){b&&!a.j&&(T(a),a.i=null,a.g.forEach(function(c,d){var e=d.toLowerCase();d!=e&&(Ua(this,d),Ua(this,e),0<c.length&&(this.i=null,this.g.set(U(this,e),qa(c)),this.h=C(this.h)+c.length))},a));a.j=b};var ab=function(a){var b=this;this.R=new Da;this.h=Xa(this);this.g=Xa(this);this.F=I("live-radio");this.da=I("sample-live-link");this.Z=I("live-inputs");this.ba=I("vod-inputs");this.J=I("vod-radio");this.la=I("sample-vod-link");this.C=I("asset-key");this.Y=I("live-api-key");this.o=I("cms-id");this.v=I("video-id");this.aa=I("vod-api-key");this.ka=I("stream-formats");this.s=I("hls-radio");this.M=I("dash-radio");this.P=I("sample-ad-tag-parameter");this.S=I("yes-include-ad-tag-parameters");this.ha=I("no-include-ad-tag-parameters");
this.j=I("ad-tag-parameters-container");this.U=I("add-ad-tag-parameter-button");this.fa=I("template-ad-tag-parameter");this.T=I("yes-include-omsdk-rules");this.ia=I("no-include-omsdk-rules");this.m=I("omsdk-rules-container");this.V=I("add-omsdk-rule-button");this.ga=I("template-omsdk-rule");this.i=I("ad-ui");this.ea=I("load-button");this.O=I("play-button");this.I=I("bookmark-button");this.W=I("bookmark-wrapper");this.ca=I("bookmark-link-text");this.A=I("console");this.N=a;this.ja=Ya(this);Za(this,
this.N);this.R.j=this.i;Ea(this.R,function(c){var d=c.type;d!=google.ima.dai.api.StreamEvent.Type.AD_PROGRESS&&b.log("Stream event: "+d);console.log("Stream event: "+d);switch(c.type){case google.ima.dai.api.StreamEvent.Type.ERROR:b.log("Stream error: "+c.getStreamData().errorMessage);break;case google.ima.dai.api.StreamEvent.Type.LOADED:b.log("Stream ID: "+c.getStreamData().streamId);break;case google.ima.dai.api.StreamEvent.Type.AD_BREAK_STARTED:b.i.style.display="block";break;case google.ima.dai.api.StreamEvent.Type.AD_BREAK_ENDED:b.i.style.display=
"none"}});$a(this)},Za=function(a,b){if(b){var c=new P(b);b=c.g.get("streamType");var d=c.g.get("streamFormat"),e=c.g.get("assetKey"),f=c.g.get("apiKey"),l=c.g.get("cmsId");c=c.g.get("videoId");b&&("live"===b.toLowerCase()?(a.J.checked=!1,a.F.checked=!0,bb(a),f&&(a.Y.value=f)):"vod"===b.toLowerCase()&&(a.J.checked=!0,a.F.checked=!1,cb(a),f&&(a.aa.value=f)));d&&("hls"===d.toLowerCase()?(a.M.checked=!1,a.s.checked=!0,db(a)):"dash"===d.toLowerCase()&&(a.M.checked=!0,a.s.checked=!1,eb(a)));e&&(a.C.value=
e);l&&(a.o.value=l);c&&(a.v.value=c)}},Xa=function(a){if(!a.h){-1!=D().indexOf("iPhone")&&-1==D().indexOf("iPod")&&-1==D().indexOf("iPad")||-1!=D().indexOf("iPad")||-1!=D().indexOf("iPod")?a.h=new M:a.h=new L;var b=a.h.g;b.addEventListener("pause",function(){var c=a.h;c.D&&(c.H(),a.i.style.display="none")});b.addEventListener("play",function(){var c=a.h;c.D&&(c.G(),a.i.style.display="block")})}return a.h},fb=function(a){if(!a.l){a.l=new O;var b=a.l.g;b.addEventListener("pause",function(){var c=a.l;
c.D&&(c.H(),a.i.style.display="none")});b.addEventListener("play",function(){var c=a.l;c.D&&(c.G(),a.i.style.display="block")})}return a.l},Ya=function(a){var b={};a=a.N.split("?")[1];if(!a)return b;a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");b[d[0]]=decodeURIComponent(d[1])}return b},$a=function(a){a.F.addEventListener("click",function(){return bb(a)});a.J.addEventListener("click",function(){return cb(a)});a.da.addEventListener("click",function(){return gb(a)});a.la.addEventListener("click",
function(){return hb(a)});a.s.addEventListener("click",function(){return db(a)});a.M.addEventListener("click",function(){return eb(a)});a.ea.addEventListener("click",function(){return ib(a)});a.O.addEventListener("click",function(){a.g.v(jb(a))});a.I.addEventListener("click",function(){if(a.g.g.currentTime){var c=a.g;c=Math.floor(c.h.contentTimeForStreamTime(c.g.currentTime));c=a.N.split("?")[0]+"?bookmark="+c}else c="Error: could not get current time of video element, or current time is 0";a.ca.value=
c;a.W.style.display="block"});a.S.addEventListener("change",function(){return kb(a)});a.ha.addEventListener("change",function(){return kb(a)});a.U.addEventListener("click",function(){return lb(a)});a.P.addEventListener("click",function(){document.querySelector(".ad-tag-parameters-choice").value="description_url";document.querySelector(".ad-tag-parameter-value").value="https://googleads.github.io/googleads-ima-html5-dai/vsi/"});var b=document.querySelector(".ad-tag-parameter");document.querySelector(".ad-tag-parameters-choice").addEventListener("input",
function(){V(b)});document.querySelector(".ad-tag-parameter-value").addEventListener("input",function(){V(b)});a.T.addEventListener("change",function(){return mb(a)});a.ia.addEventListener("change",function(){return mb(a)});a.V.addEventListener("click",function(){return nb(a)});a.ka.style.display="block"},bb=function(a){a.ba.style.display="none";a.Z.style.display="block";W(a)},cb=function(a){a.Z.style.display="none";a.ba.style.display="block";W(a)},W=function(a){a.i.style.display="none";a.O.setAttribute("disabled",
!0);a.I.setAttribute("disabled",!0)},gb=function(a){a.C.value=a.s.checked?"c-rArva4ShKVIAkNfy6HUQ":"PSzZMzAkSXCmlJOWDmRj8Q";bb(a)},hb=function(a){a.s.checked?(a.o.value="2548831",a.v.value="tears-of-steel"):(a.o.value="2559737",a.v.value="tos-dash");cb(a)},db=function(a){a.F.removeAttribute("disabled");a.l&&a.l.o();W(a);a.J.checked&&"2559737"==a.o.value&&"tos-dash"==a.v.value?hb(a):"PSzZMzAkSXCmlJOWDmRj8Q"==a.C.value&&gb(a);a.g=Xa(a);a.g.show()},eb=function(a){a.h.o();W(a);"2548831"==a.o.value&&"tears-of-steel"==
a.v.value?hb(a):"c-rArva4ShKVIAkNfy6HUQ"==a.C.value&&gb(a);a.g=fb(a);a.g.show()},kb=function(a){a.S.checked?(a.j.style.display="block",a.P.style.display="inline-block"):(a.j.style.display="none",a.P.style.display="none")},lb=function(a){var b=a.fa.content.cloneNode(!0),c=b.querySelector(".ad-tag-parameter-remove-button");a.j.appendChild(b);var d=a.j.querySelectorAll(".ad-tag-parameter:last-child")[0];d.querySelector(".ad-tag-parameters-choice").addEventListener("input",function(){V(d)});d.querySelector(".ad-tag-parameter-value").addEventListener("input",
function(){V(d)});a.j.appendChild(a.U);c.addEventListener("click",function(){d.remove()})},V=function(a){var b=a.querySelector(".ad-tag-parameters-choice"),c=a.querySelector(".ad-tag-parameter-value");a=a.querySelector(".ad-tag-parameter-warning");"cust_params"!==b.value&&"description_url"!==b.value||!c.value.includes("%")?a.style.display="none":a.style.display="block"},ob=function(a){var b={},c=a.j.querySelectorAll(".ad-tag-parameter-value");a.j.querySelectorAll(".ad-tag-parameters-choice").forEach(function(d,
e){""!==c[e].value&&(b[d.value]=c[e].value)});console.log("AdTagParameters object:",b);return b},mb=function(a){a.T.checked?a.m.classList.remove("hidden"):a.m.classList.add("hidden")},nb=function(a){var b=a.ga.content.cloneNode(!0),c=b.querySelector(".omsdk-setting-remove-button");a.m.appendChild(b);var d=a.m.querySelectorAll(".omsdk-rule:last-child")[0];a.m.appendChild(a.V);c.addEventListener("click",function(){d.remove()})},pb=function(a){var b={},c=a.m.querySelectorAll(".omsdk-verification-vendor-select"),
d=a.m.querySelectorAll(".omsdk-access-mode-select");c.forEach(function(e,f){b[google.ima.dai.api.OmidVerificationVendor[c[f].value]]=google.ima.dai.api.OmidAccessMode[d[f].value]});return b},ib=function(a){a.X=qb(a);za(a.g,function(){"live"==a.X.type?(a.I.setAttribute("disabled",!0),a.W.style.display="none"):a.I.removeAttribute("disabled");a.O.removeAttribute("disabled")});Ga(a.R,a.g,a.X);a.A.textContent=""},qb=function(a){var b=new Aa;b.i=a.s.checked?"hls":"dash";a.F.checked?(b.type="live",b.j=a.C.value,
b.g=a.Y.value):(b.type="vod",b.o=a.o.value,b.m=a.v.value,b.g=a.aa.value,b.s=jb(a));a.S.checked&&(b.h=ob(a));a.T.checked&&(b.l=pb(a));return b},jb=function(a){a=parseInt(a.ja.bookmark,10);return isNaN(a)?0:a};ab.prototype.log=function(a){var b=document.createElement("span");b.innerText=a;this.A.appendChild(b);this.A.appendChild(document.createElement("br"));this.A.scrollTop=this.A.scrollHeight};var X=["Controller"],Y=w;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);
for(var Z;X.length&&(Z=X.shift());)X.length||void 0===ab?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=ab;}).call(this);
})();